services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    command: --general-log=1 --general-log-file=/var/lib/mysql/general.log
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql_logs:/logs

  redis: # container name
    image: redis:alpine
    container_name: redis
    restart: always
    ports: # 바인딩할 포트:내부 포트
      - "6379:6379"
    volumes: # 마운트할 볼륨 설정
      - ./redis_data:/data
    command: [
      "redis-server",
      "--notify-keyspace-events", "Ex"
    ]

volumes:
  db_data:
