global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'mysql_exporter'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['mysql-exporter:9104']
  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['node-exporter:9100']