global:
  scrape_interval: 15s
  # evaluation_interval: 15s # rule evaluation 주기

scrape_configs:
  - job_name: "app"
    metrics_path: "/api/actuator/prometheus"
    static_configs:
      - targets:
          - "host.docker.internal:8080"
        labels:
          instance: "app"
  - job_name: "mysql_exporter"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["mysql-exporter:9104"]
  - job_name: "node_exporter"
    scrape_interval: 5s
    static_configs:
      - targets: ["node-exporter:9100"]
