spring:
  security:
    user:
      name: user
      password: 1234
  application:
    name: kkokkio

  data:
    redis:
      host: 127.0.0.1
      port: 6379
  config:
    import: optional:file:./.env[.properties]

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&connectTimeout=20000&useSSL=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false