name: deploy-develop

on:
  push:
    paths:
      - ".github/workflows/**"
      - "backend/src/**"
      - "backend/build.gradle"
      - "backend/settings.gradle"
      - "backend/Dockerfile.dev"
    branches:
      - develop

jobs:
  call-deploy:
    uses: ./.github/workflows/deploy-common.yml
    with:
      branch: dev
      doppler_token: ${{ secrets.DOPPLER_DEV_SERVICE_TOKEN }}
      doppler_config: dev
      tag_prefix: v-dev-
      dockerfile: Dockerfile.dev
      instance_env: dev
    secrets:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TK_GITHUB_ACCESS_TOKEN: ${{ secrets.TK_GITHUB_ACCESS_TOKEN }}
      TK_GITHUB_ACCESS_TOKEN_OWNER: ${{ secrets.TK_GITHUB_ACCESS_TOKEN_OWNER }}
