name: Assign Reviewers on PR

on:
  pull_request:
    types: [opened, reopened]

permissions:
  pull-requests: write
  issues: write

jobs:
  add_reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Assign reviewers if target is develop or main
        if: github.base_ref == 'main' || github.base_ref == 'develop'
        uses: hkusu/review-assign-action@v1
        with:
          assignees: ${{ github.actor }}
          reviewers: ${{ vars.REVIEWERS }}
          draft-keyword: wip
