name: PR SpringBoot Test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches: ["main", "develop"]
    types: [opened, reopened, ready_for_review, synchronize]

jobs:
  detect-backend-changes:
    runs-on: ubuntu-latest
    outputs:
      backend_changed: ${{ steps.filter.outputs.backend }}
    steps:
      - uses: actions/checkout@v3

      - id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            backend:
              - 'backend/**'

  springboot-test:
    needs: detect-backend-changes
    if: needs.detect-backend-changes.outputs.backend_changed == 'true'
    runs-on: ubuntu-latest

    env:
      SPRING_PROFILES_ACTIVE: test
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      JWT_EXPIRATION: ${{ secrets.JWT_EXPIRATION }}
      GOOGLE_TRENDS_RSS_URL: ${{ secrets.GOOGLE_TRENDS_RSS_URL }}
      NAMESPACE_URL: ${{ secrets.NAMESPACE_URL }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: "temurin"

      - name: Grant execute permission for gradlew
        working-directory: backend
        run: chmod +x gradlew

      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper
          cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/develop' }}

      - name: Test with Gradle
        working-directory: backend
        run: ./gradlew test

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: backend/**/build/test-results/test/TEST-*.xml

  skip-message:
    needs: detect-backend-changes
    if: needs.detect-backend-changes.outputs.backend_changed != 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Skip Spring boot tests
        run: echo "No backend changes - tests skipped ✅"
