{
 "title": "Batch",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "step",
    "label": "step",
    "query": {
     "query": "label_values(spring_batch_step_seconds_count,spring_batch_step_name)"
    }
   },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(spring_batch_step_seconds_count,spring_batch_step_job_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Job 상태",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(spring_batch_job_seconds_count[1h])",
     "legendFormat": "{{spring_batch_job_status}}"
    }
   ]
  },
  {
   "title": "최근 24h 포스트 총합",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(spring_batch_post_created[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "뉴스 API 실패율",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 5, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  increase(spring_batch_news_api_fail_total[15m])\n  /\n  (increase(spring_batch_news_api_fail_total[15m]) + increase(spring_batch_news_fetched[15m]))\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "영상 API 실패율",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 5, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  increase(spring_batch_video_api_fail_total[15m])\n  /\n  (increase(spring_batch_video_api_fail_total[15m]) + increase(spring_batch_video_fetched[15m]))\n) * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "latency ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "repeat": "step",
   "targets": [
    {
     "expr": "(\n  sum by (spring_batch_step_job_name, spring_batch_step_name) (\n    rate(\n      spring_batch_step_seconds_sum{\n        spring_batch_step_job_name=~\"$job\",\n        spring_batch_step_name=~\"$step\"\n      }[5m]\n    )\n  )\n  /\n  sum by (spring_batch_step_job_name, spring_batch_step_name) (\n    rate(\n      spring_batch_step_seconds_count{\n        spring_batch_step_job_name=~\"$job\",\n        spring_batch_step_name=~\"$step\"\n      }[5m]\n    )\n  )\n)\n* 1000\n",
     "legendFormat": "{{spring_batch_step_name}}"
    }
   ]
  },
  {
   "title": "latency p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(spring_batch_step_seconds_bucket{spring_batch_step_name=~\"$step\"}[5m])) by (le))\n* 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Entry 수",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    { "expr": "spring_batch_cache_size", "legendFormat": "{{bucket}}" }
   ]
  },
  {
   "title": "시간대별 포스트 생성량",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "increase(spring_batch_post_created[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "“포스트 스킵” 주기 ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    { "expr": "spring_batch_no_post_needed", "legendFormat": "No post needed" }
   ]
  },
  {
   "title": "Low-Variation 수",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "increase(spring_batch_post_created[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}